#
#   Author: Rohith
#   Date: 2015-07-17 14:38:11 +0100 (Fri, 17 Jul 2015)
#
#  vim:ts=2:sw=2:et
#
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: mail
spec:
  replicas: 1
  selector:
    name: mail
  template:
    metadata:
      labels:
        name: mail
    spec:
      containers:
      - name: postfix
        image: gambol99/postfix:latest
        ports:
        - containerPort: 25
        env:
        - name: TLS_ENABLED
          value: 'TRUE'
        - name: TLS_CERT_FILE
          value: /etc/secrets/certs/postfix-cert
        - name: TLS_KEY_FILE
          value: /etc/secrets/certs/postfix-key
        - name: TLS_SASL_PASSWD
          value: /etc/secrets/sasl/postfix-sasl
        - name: RELAY_HOST
          value: email-smtp.eu-west-1.amazonaws.com:25
        - name: MYHOSTNAME
          value: mail
        - name: MYDOMAIN
          value: exmaple.com
        volumeMounts:
        - name: certs
          mountPath: /etc/secrets/certs
        - name: sasl
          mountPath: /etc/secrets/sasl
      volumes:
      - name: certs
        secret:
          secretName: mail-certs
      - name: sasl
        secret:
          secretName: mail-sasl
